config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#homepage'

  devise_for :users,
             controllers: {
               confirmations: 'confirmations',
               registrations: 'registrations',
               sessions: 'sessions'
             }

  resources :comments, only: %i[edit create update destroy]
  resources :ratings, only: %i[create update]

  get 'hunts/:id/join/:token', to: 'hunts#join', as: :join_hunt
  post 'hunts/:id/join/:token', to: 'hunts#join', as: :join_accept_hunt

  resources :hunts, only: %i[create index show] do
    resources :homes do
      patch :restore, on: :member
      patch :refresh_listing, on: :member
    end
  end
end

app/models/hunt.rb
# frozen_string_literal: true

class Hunt < ApplicationRecord
  include Hashid::Rails

  belongs_to :creator_user, class_name: 'User'
  has_many :homes, dependent: :destroy
  has_many :hunt_memberships, dependent: :destroy

  validates :title, presence: true

  auto_strip_attributes :title, squish: true

  def token_match?(test_token)
    return false if test_token.blank?

    test_token.squish == join_token
  end
end

app/controllers/hunts_controller.rb
# frozen_string_literal: true

class HuntsController < ApplicationController
  before_action :set_hunt, only: %i[show]

  skip_before_action :authenticate_user!, only: %i[join]

  def index
    @hunts = current_user.hunts.includes(:creator_user)
  end

  def show; end

  def join
    @hunt = Hunt.find_by_hashid(params[:id])

    unless @hunt.token_match?(params[:token])
      return redirect_to root_path, alert: 'This invite link is incorrect or has expired.'
    end

    return if join_hunt

    store_location

    render :join
  end

  def create
    @hunt = Hunt.new(hunt_params)
    @hunt.creator_user = current_user

    if @hunt.save
      current_user.hunt_memberships.create(hunt: @hunt)
      redirect_to hunt_path(@hunt), notice: 'Hunt was successfully created.'
    else
      render :new
    end
  end

  private

  def set_hunt
    @hunt = current_user.hunts.find_by_hashid!(params[:id])
  end

  def join_hunt
    return false unless user_signed_in? && params[:confirm] == 'true'

    msg = if current_user.hunt_member?(@hunt)
            "You've already joined this hunt"
          else
            current_user.hunt_memberships.create!(hunt: @hunt)
            "You're in! Get hunting!"
          end
    redirect_to hunt_path(@hunt), notice: msg

    true
  end

  def hunt_params
    params.require(:hunt).permit(
      :title
    )
  end
end

app/views/hunts/_action_buttons.html.erb
<% if hunt.homes.where(disabled: false).size.positive? %>
  <%= link_to 'Add home',
              new_hunt_home_path(hunt),
              class: 'btn btn-success' %>
  <%= link_to "View #{pluralize(hunt.homes.where(disabled: false).size, 'home')}",
              hunt_homes_path(hunt),
              class: 'btn btn-success' %>
<% else %>
  <%= link_to 'Add the first home',
              new_hunt_home_path(hunt),
              class: 'btn btn-success' %>
<% end %>

app/views/hunts/_details.html.erb
<h4>
  <%= hunt.title %>
</h4>

<div class="row">
  <% hunt.hunt_memberships.includes(:user).find_each do |hm| %>
    <div class="col-12 col-md-6 col-lg-4">
      <div class="media mt-2 mb-2">
        <%= image_tag hm.user.gravatar_url(70),
                      class: 'mr-3 rounded',
                      size: 70 %>
        <div class="media-body">
          <h5 class="mt-0 mb-0">
            <%= hm.user.display_name %>
          </h5>
          <p>
            <% if hm.user == hunt.creator_user %>
              started on
              <%= hunt.created_at.strftime('%d %b %Y') %>
            <% else %>
              joined on
              <%= hm.created_at.strftime('%d %b %Y') %>
            <% end %>
            <br>
            added
            <%= fa_icon_inline('home') %>
            <%= hunt.homes.where(disabled: false).where(creator_user: hm.user).size %>
            &nbsp;
            <%= fa_icon_inline('comments') %>
            <%= hm.user.comments.where(home: hunt.homes).size %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/hunts/_form.html.erb
<%= form_with model: hunt do |f| %>
  <div class="input-group">
    <%= f.text_field :title,
                     class: 'form-control',
                     placeholder: 'My first home hunt',
                     required: true %>
    <div class="input-group-append">
      <%= f.submit 'Start hunting!', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/hunts/index.html.erb
<h3>Your Home Hunts</h3>

<p>
  You can hunt for homes on your own, or together with other people.
</p>

<% if @hunts.each do |hunt| %>
  <%= render 'details', hunt: hunt %>
  <%= link_to 'View details',
              hunt_path(hunt),
              class: 'btn btn-success' %>
  <%= render 'action_buttons', hunt: hunt %>
<% end.empty? %>
  <p>
    You haven't set up or joined any hunts yet.
    Creating a hunt lets you build a list of homes and invite others to collaborate.
  </p>
<% end %>

<h3 class="mt-4">
  Begin a new hunt!
</h3>

<%= render 'form', hunt: current_user.hunts.new %>

<h3 class="mt-4">
  Already been invited?
</h3>

<p>
  Click the link you were sent and you'll be able to accept the invite.
</p>

app/views/hunts/join.html.erb
<% title "Join my hunt for '#{@hunt.title}'" %>
<% meta_tag :description, "Collaborate with #{@hunt.creator_user.display_name} on their search for a home!" %>

<p class="mt-3">
  <%= @hunt.creator_user.display_name %>
  has invited you to help find a home through HomePicker!
</p>

<%= render 'layouts/about_blurb' %>

<%= render 'details', hunt: @hunt %>

<% if user_signed_in? %>
  <%= link_to "Join hunt: #{@hunt.title}",
              join_accept_hunt_path(@hunt, token: params[:token], confirm: 'true'),
              method: :post,
              class: 'btn btn-success' %>
<% else %>
  <p>
    You'll need to
    <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary' %>
    or
    <%= link_to 'Log In', new_user_session_path, class: 'btn btn-primary' %>
    before you can join the hunt.
  </p>
<% end %>

app/views/hunts/show.html.erb
<% title @hunt.title %>

<%= render 'details', hunt: @hunt %>

<%= render 'action_buttons', hunt: @hunt %>

<p class="mt-3">
  To invite others to this home hunt,
  share the following link:
</p>

<p>
  <code><%= join_hunt_url(@hunt, token: @hunt.join_token) %></code>
</p>