config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#homepage'

  devise_for :users,
             controllers: {
               confirmations: 'confirmations',
               registrations: 'registrations',
               sessions: 'sessions'
             }

  resources :comments, only: %i[edit create update destroy]
  resources :ratings, only: %i[create update]

  get 'hunts/:id/join/:token', to: 'hunts#join', as: :join_hunt
  post 'hunts/:id/join/:token', to: 'hunts#join', as: :join_accept_hunt

  resources :hunts, only: %i[create index show] do
    resources :homes do
      patch :restore, on: :member
      patch :refresh_listing, on: :member
    end
  end
end

app/models/home.rb
# frozen_string_literal: true

class Home < ApplicationRecord
  include Hashid::Rails

  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :images, dependent: :destroy

  belongs_to :hunt, optional: false
  belongs_to :creator_user, class_name: 'User', optional: false

  validates :title, presence: true
  validates :address_street, presence: true
  validates :price, presence: true

  default_scope { order(:id) }

  has_paper_trail only: %i[price listing_status]

  auto_strip_attributes :address_street, squish: true
  auto_strip_attributes :address_locality, squish: true
  auto_strip_attributes :address_region, squish: true
  auto_strip_attributes :agent_url, squish: true
  auto_strip_attributes :postcode, squish: true
  auto_strip_attributes :rightmove_url, squish: true
  auto_strip_attributes :title, squish: true
  auto_strip_attributes :zoopla_url, squish: true
  auto_strip_attributes :description

  accepts_nested_attributes_for :images, reject_if: :mark_empty_images_for_destruction, allow_destroy: true

  enum listing_status: { okay: 0, removed: 1 }, _prefix: :listing

  def default_thumb
    images.first&.thumb_url_fallback || placeholder_image
  end

  def placeholder_image
    'https://homepicker.s3.eu-west-2.amazonaws.com/homepicker.svg'
  end

  def average_rating
    return nil if ratings.none?

    scores = ratings.map(&:score)

    (scores.sum * 10.0 / scores.count).round / 10.0
  end

  def mark_empty_images_for_destruction(attributes)
    exists = attributes['id'].present?
    empty = attributes.except(:id).values.all?(&:blank?)
    attributes[:_destroy] = 1 if exists && empty # destroy empty images

    !exists && empty # reject empty attributes
  end

  def price_display
    return 'UNKNOWN PRICE' if price.zero?

    # Assume monthly rental amount if < 10k
    if price >= 1_000_000
      "£#{price / 1_000_000.0}m"
    elsif price > 10_000
      "£#{price / 1000}k"
    else
      "£#{price} pcm"
    end
  end

  def rightmove_search_link
    return nil if postcode.blank?

    "https://www.rightmove.co.uk/property-for-sale/search.html?searchLocation=#{postcode}&includeSSTC=true"
  end

  def zoopla_search_link
    return nil if postcode.blank?

    "https://www.zoopla.co.uk/search/?q=#{postcode}&include_sold=true&section=for-sale"
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  before_action :set_home, only: %i[show edit update destroy restore refresh_listing]
  before_action :set_hunt

  before_action :store_location, only: %i[index show new edit]

  skip_before_action :authenticate_user!, only: %i[show refresh_listing]

  def index
    filter_disabled = params[:disabled] == 'true'
    @homes = @hunt.homes.where(disabled: filter_disabled).includes(:ratings)
  end

  def show
    @ratings = Rating.aspects.keys.map do |aspect|
      Rating.find_or_initialize_by(user: current_user, home: @home, aspect:)
    end

    @others_ratings = @home.ratings.where.not(user: current_user).includes(:user).to_a
  end

  def new
    @home = @hunt.homes.new
  end

  def edit; end

  def create
    @home = Home.new(home_params)
    @home.creator_user = current_user

    retrieve_attributes_from_url

    # Avoid saving a duplicate of existing home
    return if redirect_to_duplicate?

    if @home.save
      ImageService.persist_images(@home, @images)
      redirect_to hunt_home_path(@hunt, @home), notice: 'Home was successfully created.'
    else
      render :new
    end
  end

  def update
    if @home.update(home_params)
      redirect_to hunt_home_path(@hunt, @home), notice: 'Home was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @home.update!(disabled: true)
    redirect_to hunt_homes_path(@hunt), notice: 'Home archived!'
  end

  def restore
    @home.update!(disabled: false)
    redirect_to hunt_home_path(@hunt, @home), notice: 'Home restored!'
  end

  def refresh_listing
    fls = if @home.rightmove_url.present?
            refresh_listing_from_rightmove
          else
            { alert: 'Cannot refresh listing for non-rightmove homes!' }
          end
    redirect_to hunt_home_path(@hunt, @home), flash: fls
  end

  private

  def redirect_to_duplicate?
    redirect_to_duplicate_rightmove? || redirect_to_duplicate_zoopla?
  end

  def redirect_to_duplicate_rightmove?
    return false if @home.rightmove_url.nil?

    existing_rm_home = @home.hunt&.homes&.find_by(rightmove_url: @home.rightmove_url)
    if existing_rm_home.present?
      # Fallback persistance of images in case of previous omissions
      ImageService.persist_images(existing_rm_home, @images)
      redirect_to(hunt_home_path(@hunt, existing_rm_home), alert: 'Home already imported from Rightmove; see below.')
      return true
    end

    false
  end

  def redirect_to_duplicate_zoopla?
    return false if @home.zoopla_url.nil?

    existing_z_home = @home.hunt&.homes&.find_by(zoopla_url: @home.zoopla_url)
    if existing_z_home.present?
      ImageService.persist_images(existing_z_home, @images)
      redirect_to(hunt_home_path(@hunt, existing_z_home), alert: 'Home already imported from Zoopla; see below.')
      return true
    end

    false
  end

  def retrieve_attributes_from_url
    return if params[:url].nil?

    retrieved_data = LinkRetrieverService.retrieve(params[:url])
    @images = retrieved_data.delete(:images)
    @home.assign_attributes(retrieved_data.except(:floorplans, :key_features))
  end

  def refresh_listing_from_rightmove
    rm_data = LinkRetrieverService.retrieve(@home.rightmove_url)
    new_status = rm_data.fetch(:listing_status)
    if @home.update(listing_status: new_status)
      has_changed = @home.saved_change_to_attribute?(:listing_status)
      { notice: "#{has_changed ? 'Updated status to ' : 'Status is still '} '#{@home.listing_status}'" }
    else
      { alert: "Failed to update: #{@home.errors.full_messages.join(',')}" }
    end
  end

  def set_home
    @home = Home.find_by_hashid!(params[:id])
  end

  def set_hunt
    @hunt = Hunt.find_by_hashid!(params[:hunt_id])
  end

  def home_params
    HomeParams.new(params).permitted
  end
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
  def render_home_changeset_price(version)
    return unless version.changeset.key?('price')

    from, to = version.changeset['price']

    prefix = "#{version.created_at.strftime('%d/%m/%Y')} : Price "

    return tag.p("#{prefix} set to #{to}.") if from.nil?

    tag.p("#{prefix} #{from.to_i > to.to_i ? 'decreased' : 'increased'} from #{from} to #{to}.")
  end

  def render_home_changeset_listing_status(version)
    return unless version.changeset.key?('listing_status')

    from, to = version.changeset['listing_status']

    prefix = "#{version.created_at.strftime('%d/%m/%Y')} : Listing status "

    return tag.p("#{prefix} set to #{to}.") if from.nil?

    tag.p("#{prefix} changed from #{from} to #{to}.")
  end
end

app/views/homes/_form.html.erb
<%= form_with model: [@hunt, home] do |f| %>
  <%= render 'layouts/errors', errors: home.errors %>

  <div class="form-row">
    <div class="form-group col-md-9">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', autocomplete: 'off' %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :price %>
      <%= f.number_field :price, class: 'form-control', step: 1, autocomplete: 'off' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :address_street %>
      <%= f.text_field :address_street, class: 'form-control', autocomplete: 'off' %>
    </div>
    <div class="form-group col-6 col-md-3">
      <%= f.label :latitude %>
      <%= f.text_field :latitude, class: 'form-control', inputmode: 'numeric', autocomplete: 'off' %>
    </div>
    <div class="form-group col-6 col-md-3">
      <%= f.label :longitude %>
      <%= f.text_field :longitude, class: 'form-control', inputmode: 'numeric', autocomplete: 'off' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-4">
      <%= f.label :address_locality %>
      <%= f.text_field :address_locality, class: 'form-control' %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :address_region %>
      <%= f.text_field :address_region, class: 'form-control' %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :postcode %>
      <%= f.text_field :postcode, class: 'form-control', autocomplete: 'off' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', rows: 10, autocomplete: 'off' %>
  </div>

  <div class="form-row">
    <div class="form-group col-md-4">
      <%= f.label :agent_url %>
      <%= f.text_field :agent_url, class: 'form-control' %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :zoopla_url %>
      <% if f.object&.zoopla_search_link.present? %>
        <div class="input-group">
          <%= f.text_field :zoopla_url,
                           class: 'form-control',
                           placeholder: 'https://zoopla.co.uk/...',
                           autocomplete: 'off' %>
          <div class="input-group-append">
            <%= link_to fa_icon_inline('search'),
                        f.object.zoopla_search_link,
                        class: 'btn btn-outline-secondary',
                        type: :button,
                        target: :_blank,
                        rel: :noopener,
                        data: { toggle: :tooltip },
                        title: 'Search Zoopla for this property' %>
          </div>
        </div>
      <% else %>
        <%= f.text_field :zoopla_url,
                         class: 'form-control',
                         placeholder: 'https://zoopla.co.uk/...',
                         autocomplete: 'off' %>
      <% end %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :rightmove_url %>
      <% if f.object&.rightmove_search_link.present? %>
        <div class="input-group">
          <%= f.text_field :rightmove_url,
                           class: 'form-control',
                           placeholder: 'https://rightmove.co.uk/...',
                           autocomplete: 'off' %>
          <div class="input-group-append">
            <%= link_to fa_icon_inline('search'),
                        f.object.rightmove_search_link,
                        class: 'btn btn-outline-secondary',
                        type: :button,
                        target: :_blank,
                        rel: :noopener,
                        data: { toggle: :tooltip },
                        title: 'Search Rightmove for this property' %>
          </div>
        </div>
      <% else %>
        <%= f.text_field :rightmove_url,
                         class: 'form-control',
                         placeholder: 'https://rightmove.co.uk/...',
                         autocomplete: 'off' %>
      <% end %>
    </div>

  </div>

  <div class="form-row">
    <%= f.fields_for :images do |images_form| %>
      <% if images_form.object.persisted? %>
        <div class="form-group col-md-3">
          <%= images_form.label :_destroy do %>
            <%= image_tag images_form.object.thumb_url_fallback, class: 'img-thumbnail' %>
          <% end %>
          <%= images_form.check_box :_destroy, class: 'form-check-input' %>
          <%#= images_form.label :_destroy, class: 'form-check-label' %>
          <br>
          <%= images_form.text_field :external_url, disabled: true, class: 'form-control' %>
        </div>
      <% else %>
        <div class="form-group col-md-3">
          <%= image_tag images_form.object.thumb_url_fallback, class: 'img-thumbnail' %>
          <%= images_form.text_field :external_url, class: 'form-control' %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :bulk_images do %>
      Bulk Images
      <small>(enter each new image URL on its own line)</small>
    <% end %>
    <%= f.text_area :bulk_images, class: 'form-control', rows: 4, autocomplete: 'off' %>
  </div>

  <%= f.hidden_field :hunt_id, value: @hunt.hashid %>
  <%= f.submit class: 'btn btn-primary' %>

  <%= link_to 'Cancel',
              (home.new_record? ? hunt_homes_path(@hunt) : hunt_home_path(@hunt, @home)),
              class: 'btn btn-light' %>
<% end %>

app/views/homes/_homes_map.html.erb
<script src="https://api.mapbox.com/mapbox-gl-js/v1.10.0/mapbox-gl.js"></script>
<link href="https://api.mapbox.com/mapbox-gl-js/v1.10.0/mapbox-gl.css" rel="stylesheet" />

<div id="mapbox_map" style="padding-top: 20px; height: 500px"></div>

<script>
  <%# Taken from: https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/ %>
  mapboxgl.accessToken = '<%= ENV.fetch('MAPBOX_TOKEN', 'no mapbox token ') %>';

  var map = new mapboxgl.Map({
    container: 'mapbox_map',
    style: 'mapbox://styles/mapbox/streets-v11',
    center: [<%= homes.first.longitude %>, <%= homes.first.latitude %>],
    zoom: 14
  });

  map.on('load', function() {
    map.addSource('places', {
      'type': 'geojson',
      'data': {
        'type': 'FeatureCollection',
        'features': [
          <% homes.each do |home| %>
          {
            'type': 'Feature',
            'properties': {
              'description': '<strong><%= home.address_street %></strong><p><a href="<%= hunt_home_path(@hunt, home) %>"><%= home.title %></a> </p>',
              'icon': 'rocket'
            },
            'geometry': {
              'type': 'Point',
              'coordinates': [<%= home.longitude %>, <%= home.latitude %>]
            }
          },
          <% end %>
        ]
      }
    });
    // Add a layer showing the places.
    map.addLayer({
      'id': 'places',
      'type': 'symbol',
      'source': 'places',
      'layout': {
        'icon-image': '{icon}-15',
        'icon-allow-overlap': true
      }
    });

    // When a click event occurs on a feature in the places layer, open a popup at the
    // location of the feature, with description HTML from its properties.
    map.on('click', 'places', function(e) {
      var coordinates = e.features[0].geometry.coordinates.slice();
      var description = e.features[0].properties.description;

      // Ensure that if the map is zoomed out such that multiple
      // copies of the feature are visible, the popup appears
      // over the copy being pointed to.
      while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
        coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360;
      }

      new mapboxgl.Popup()
        .setLngLat(coordinates)
        .setHTML(description)
        .addTo(map);
    });

    // Change the cursor to a pointer when the mouse is over the places layer.
    map.on('mouseenter', 'places', function() {
      map.getCanvas().style.cursor = 'pointer';
    });

    // Change it back to a pointer when it leaves.
    map.on('mouseleave', 'places', function() {
      map.getCanvas().style.cursor = '';
    });
  });
</script>

app/views/homes/_images_carousel.html.erb
<%# Based on https://stackoverflow.com/questions/41548027 %>

<div id="homeImagesCarousel" class="carousel carousel-fade" data-interval="false">
  <%# Carousel full-size images %>
  <div class="carousel-inner shadow">
    <% images.each_with_index do |image, idx| %>
      <div class="<%= 'active' if idx.zero? %> carousel-item" data-slide-number="<%= idx %>">
        <%= image_tag image.full_url_fallback, class: 'd-block w-100', alt: "Image #{idx + 1} of #{images.size}" %>
      </div>
    <% end %>

    <a class="carousel-control-prev" href="#homeImagesCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#homeImagesCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <%# Carousel thumbnails %>
  <ul class="carousel-indicators list-inline mx-auto px-2 mb-0 d-none d-md-flex">
    <% images.each_with_index do |image, idx| %>
      <li class="list-inline-item <%= 'active' if idx.zero? %>">
        <%= link_to nil,
                    id: "carousel-selector-#{idx}",
                    class: idx.zero? ? 'selected' : '',
                    data: { 'slide-to': idx, target: '#homeImagesCarousel' } do %>
          <%= image_tag image.thumb_url_fallback, class: 'img-fluid', style: 'max-height: 100px;', alt: "Image #{idx + 1} of #{images.size}" %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/homes/_import_form.html.erb
<%= form_with model: [@hunt, home] do |f| %>
  <%= render 'layouts/errors', errors: home.errors %>

  <p>
    To quickly add a home to the
    <strong><%= @hunt.title %></strong> hunt,
    paste the Rightmove or Zoopla link below.
  </p>

  <div class="form-group">
    <label for="url">Retrieve Data via URL</label>
    <%= text_field_tag :url,
                       params[:url],
                       class: 'form-control',
                       placeholder: 'https://zoopla.co.uk/... or https://rightmove.co.uk/...',
                       required: true,
                       autofocus: true %>
  </div>

  <%= f.hidden_field :hunt_id, value: @hunt.hashid %>
  <%= f.submit 'Import Home Details', class: 'btn btn-primary' %>
  or
  <%= link_to 'Enter manually',
              new_hunt_home_path(manual: true),
              class: 'btn btn-outline-dark' %>
<% end %>

<% if params[:url].nil? %>
  <p class="mt-3">
    You can also save this bookmark -
    <%= link_to "Add to #{@hunt.title}",
                "javascript:window.location='#{new_hunt_home_url}?url='+ window.location;" %>
    - and click it from any Zoopla/Rightmove page to save to this hunt.
  </p>
<% end %>

app/views/homes/_link_icons.html.erb
<% verbose ||= false %>
<% if home.latitude.present? && home.longitude.present? %>
  <%= link_to image_tag('external-icons/google-maps.svg', size: 30, alt: 'Google Maps', title: 'View location on Google Maps'),
              "https://www.google.co.uk/maps/place/#{home.latitude},#{home.longitude}" %>
  <% if verbose %>
    <%= link_to image_tag('external-icons/shademap.png', size: 30, class: 'rounded', alt: 'Shademap', title: 'View sun position over time on Shademap'),
                "https://shademap.app/@#{home.latitude},#{home.longitude},18z,#{Time.zone.now.to_i}000t" %>
  <% end %>
<% end %>
<% if home.zoopla_url.present? %>
  <%= link_to image_tag('external-icons/zoopla.png', size: 30, class: 'rounded', alt: 'Zoopla', title: 'View property on Zoopla'),
              home.zoopla_url %>
<% end %>
<% if home.rightmove_url.present? %>
  <%= link_to image_tag('external-icons/rightmove.png', size: 30, class: 'rounded', alt: 'Rightmove', title: 'View property on Rightmove'),
              home.rightmove_url %>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

app/views/homes/index.html.erb
<% title "Homes | #{@hunt.title}" %>

<h3>Homes - <%= @hunt.title %></h3>

<% if @homes.each do |home| %>
  <div class="media">
    <%= link_to hunt_home_path(@hunt, home), class: 'align-self-center' do %>
      <%= image_tag home.default_thumb, height: 100, class: 'mr-3', alt: home.address_street %>
    <% end %>
    <div class="media-body">
      <h5 class="mt-0">
        <%= link_to home.address_street, hunt_home_path(@hunt, home) %>
        <%= home.price_display %>
      </h5>
      <p class="mb-2"><%= home.title %><%= ", #{home.postcode}" if home.postcode.present? %></p>
      <p>
        <%= render 'link_icons', home: home %>
        <% if home.listing_removed? %>
          &nbsp;
          <%= fa_icon_inline('exclamation-circle', type: :solid, cls: 'text-danger') %>
        <% end %>
        <% if home.average_rating %>
          &nbsp;
          <%= fa_icon_inline('star', cls: 'text-warning') %> <%= home.average_rating %>
        <% end %>
        <% if home.comments.any? %>
          &nbsp;
          <%= fa_icon_inline(home.comments.size == 1 ? 'comment' : 'comments', cls: 'text-success') %> <%= home.comments.size %>
        <% end %>
      </p>
    </div>
  </div>
<% end.empty? %>
  <p>
    No homes!
    Get started by
    <%= link_to 'adding one', new_hunt_home_path(@hunt) %>.
  </p>
<% end %>

<div class="mt-3">
  <% longlat_homes = @homes.select { |x| x.latitude.present? && x.longitude.present? } %>
  <%= render 'homes_map', homes: longlat_homes if longlat_homes.any? %>
</div>

app/views/homes/new.html.erb
<% title 'Add Home' %>

<h3>Add Home to <%= @hunt.title %></h3>

<% # display full form if submitted with errors %>
<% if params[:manual] == 'true' || @home.errors.any? %>
  <%= render 'form', home: @home %>
<% else %>
  <%= render 'import_form', home: @home %>
<% end %>

app/views/homes/show.html.erb
<% title @home.address_street || @home.title %>

<% if @home.disabled? %>
  <div class="mt-4 alert alert-danger" role="alert">
    This home has been archived.
  </div>
<% end %>

<div class="row mt-2">
  <div class="col-sm-8">
    <h1>
      <%= @home.address_street || '[unnamed property]' %>
    </h1>
    <h3>
      <%= [@home.title, @home.postcode].compact.join(', ') %>
    </h3>
    <p>
      <%= [@home.address_locality, @home.address_region].compact.join(', ') %>
    </p>
  </div>
  <div class="col-sm-4 text-right">
    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_hunt_home_path(@hunt, @home), class: 'btn btn-warning' %>
    <% else %>
      <%= link_to 'Log in', new_session_path('user'), class: 'btn btn-warning' %>
    <% end %>
    <% if @home.disabled? %>
      <%= link_to 'Restore',
                  restore_hunt_home_path(@hunt, @home),
                  method: :patch,
                  class: 'btn btn-info' %>
    <% else %>
      <% if @home.rightmove_url.present? %>
        <%= link_to 'Refresh Listing Status',
                    refresh_listing_hunt_home_path(@hunt, @home),
                    method: :patch,
                    class: 'btn btn-info' %>
        <% end %>
      <% if user_signed_in? %>
        <%= link_to 'Archive',
                    hunt_home_path(@hunt, @home),
                    method: :delete,
                    data: { confirm: 'Really archive this home?' },
                    class: 'btn btn-danger' %>
      <% end %>
    <% end %>

    <h3><%= @home.price_display %></h3>
    <p>
      <%= render 'link_icons', home: @home, verbose: true %>
    </p>
  </div>
</div>

<% if @home.listing_removed? %>
  <div class="alert alert-danger" role="alert">
    This listing has been removed by the agent
  </div>
<% end %>

<div class="row">
  <div class="col-12 col-lg-8">
    <% if @home.images.any? %>
      <%= render 'images_carousel', images: @home.images %>
    <% else %>
      <div class="alert alert-danger" role="alert">
        There aren't any images for this home.
      </div>
    <% end %>
  </div>
  <div class="col-12 col-lg-4">
    <%= render 'comments/list', comments: @home.comments %>
    <% if user_signed_in? %>
      <%= render 'comments/form', comment: @home.comments.new %>
    <% else %>
      <p>
        <%= link_to 'Log in', new_session_path('user') %>
        to leave a comment or rating.
      </p>
    <% end %>

    <% @ratings.each do |rating| %>
      <br>
      <%= render 'ratings/form',
                 rating: rating,
                 others_ratings: @others_ratings.select { |x| x.aspect == rating.aspect} %>
    <% end %>
  </div>
</div>

<div class="mt-3">
  <h3>Details</h3>
  <% if @home.description.present? %>
    <%= render_markdown_paragraphs(@home.description) %>
  <% else %>
    NO DETAILS
  <% end %>
</div>

<% if @home.latitude.present? && @home.longitude.present? %>
  <script src="https://api.mapbox.com/mapbox-gl-js/v1.10.0/mapbox-gl.js"></script>
  <link href="https://api.mapbox.com/mapbox-gl-js/v1.10.0/mapbox-gl.css" rel="stylesheet" />

  <div id="mapbox_map" style="padding-top: 20px; height: 500px"></div>

  <script>
    mapboxgl.accessToken = '<%= ENV.fetch('MAPBOX_TOKEN', 'no mapbox token') %>';

    var map = new mapboxgl.Map({
    container: 'mapbox_map',
    style: 'mapbox://styles/mapbox/streets-v11',
    center: [<%= @home.longitude %>, <%= @home.latitude %>],
    zoom: 14
    });

    var marker = new mapboxgl.Marker()
    .setLngLat([<%= @home.longitude %>, <%= @home.latitude %>])
    .addTo(map);
  </script>
<% end %>

<div class="mt-3">
  <h3>History</h3>

  <p>
    <%= @home.created_at.strftime('%d/%m/%Y') %> : Home added to the <%= link_to @hunt.title, hunt_path(@hunt) %> hunt by <%= @home.creator_user.display_name %>.
  </p>
  <% @home.versions.each do |version| %>
    <%= render_home_changeset_price(version) %>
    <%= render_home_changeset_listing_status(version) %>
  <% end %>
</div>