config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#homepage'

  devise_for :users,
             controllers: {
               confirmations: 'confirmations',
               registrations: 'registrations',
               sessions: 'sessions'
             }

  resources :comments, only: %i[edit create update destroy]
  resources :ratings, only: %i[create update]

  get 'hunts/:id/join/:token', to: 'hunts#join', as: :join_hunt
  post 'hunts/:id/join/:token', to: 'hunts#join', as: :join_accept_hunt

  resources :hunts, only: %i[create index show] do
    resources :homes do
      patch :restore, on: :member
      patch :refresh_listing, on: :member
    end
  end
end

app/views/layouts/_about_blurb.html.erb
<p>
  HomePicker helps people collaborate on their property search
  by building a shortlist of homes together.
</p>


<ul class="list-unstyled">
  <li>
    <%= fa_icon_inline('list-alt', type: :light) %>
    Quickly pull in listings from Zoopla or Rightmove.
  </li>
  <li>
    <%= fa_icon_inline('comments', type: :light) %>
    Share comments or ratings to discover what each of you like.
  </li>
  <li>
    <%= fa_icon_inline('heart', type: :light) %>
    Find the place you all fall in love with!
  </li>
</ul>

app/views/layouts/_errors.html.erb
<% errors.full_messages.each do |message| %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">
      &copy; Ollie Bennett
      <% if @home&.zoopla_url.present? %>
        / Zoopla
      <% end %>
      <% if @home&.rightmove_url.present? %>
        / Rightmove
      <% end %>
      <!-- Logo: 'Home' by Dron Desain from the Noun Project -->
    </span>
  </div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= csrf_meta_tags %>

  <meta name='description' content='<%= content_for(:meta_description) || 'Collaborate on the search for your home!' %>' />

  <title>
    <%= if content_for?(:title) then yield(:title) + ' | ' end %>HomePicker
  </title>

  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
        crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/site.webmanifest">

  <%= javascript_include_tag 'application' %>

  <script>
    (function(s,q,e,a,u,k,y){
      s._sqSettings={site_id:'e54a2bab-2cb5-46e9-bf25-1325729622ce'};
      u=q.getElementsByTagName('head')[0];
      k=q.createElement('script');
      k.src=e+s._sqSettings.site_id;
      u.appendChild(k);
    })(window,document,'https://cdn.squeaky.ai/g/0.4.0/script.js?');
  </script>
</head>

app/views/layouts/_javascripts.html.erb
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
        integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
        crossorigin="anonymous"></script>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-light bg-warning pt-0 mb-3">
  <div class="container">
    <% if user_signed_in? %>
      <div class="navbar-nav">
        <% if @hunt %>
          <%= link_to hunt_homes_path(@hunt), class: 'nav-item nav-link pr-3' do %>
            <%= fa_icon_inline('list') %>
            <span class="d-none d-lg-inline-block">Homes</span>
          <% end %>
        <% end %>
      </div>
      <div class="navbar-nav">
        <% if @hunt %>
          <%= link_to new_hunt_home_path(@hunt), class: 'nav-item nav-link pl-3 pr-3' do %>
            <%= fa_icon_inline('plus') %>
            <span class="d-none d-lg-inline-block">New Home</span>
          <% end %>
        <% end %>
      </div>
      <div class="navbar-nav">
        <% if @hunt %>
          <%= link_to hunts_path, class: 'nav-item nav-link pl-3 pr-3' do %>
            <%= fa_icon_inline('exchange') %>
            <span class="d-none d-lg-inline-block">Switch Hunt</span>
          <% end %>
        <% end %>
      </div>
      <div class="navbar-nav">
        <%= link_to destroy_user_session_path,
                    method: :delete,
                    data: { confirm: 'Really sign out?' },
                    class: 'nav-item nav-link pl-3' do %>
          <%= fa_icon_inline('sign-out-alt') %>
          <span class="d-none d-lg-inline-block">Sign out</span>
        <% end %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value|

  # Convert devise keys into bootstrap-compatible styles
  alert_class = case key.to_s
  when "notice"
    "success"
  when "alert"
    "warning"
  when "error"
    "danger"
  else
    key.to_s
  end
  %>
  <div class="alert alert-<%= alert_class %> alert-dismissible mt-3" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>
  <body class="bg-light">
    <div class="bg-warning text-center pt-3">
      <a class="header-text nav-light nav-link" href="/">
        <%= image_tag 'https://homepicker.s3.eu-west-2.amazonaws.com/homepicker.svg',
                      class: 'd-inline-block align-top',
                      alt: 'Logo' %>
        HomePicker
      </a>
    </div>
    <%= render 'layouts/menu' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/javascripts' %>
  </body>
</html>

app/views/layouts/minimal.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>
  <body class="bg-light">
    <div class="container">
      <%= render 'layouts/messages' %>

      <div style="text-align: center;" class="mt-4 pt-4">
        <%= image_tag 'https://homepicker.s3.eu-west-2.amazonaws.com/homepicker.svg', size: 150, alt: 'Logo' %>
        <%= yield %>
      </div>

    </div>
    <%= render 'layouts/javascripts' %>
  </body>
</html>